sudo: required

language: bash

services:
  - docker

install:
  - docker build -t quay.io/azavea/spark:${TRAVIS_COMMIT:0:7} .

script:
  - docker run --rm quay.io/azavea/spark:${TRAVIS_COMMIT:0:7} spark-shell

after_success:
  - docker login -e . -p "${QUAY_PASSWORD}" -u "${QUAY_USER}" quay.io
  - if [ "${TRAVIS_BRANCH}" == "develop" ]; then
    docker push quay.io/azavea/spark:${TRAVIS_COMMIT:0:7};
    docker tag quay.io/azavea/spark:${TRAVIS_COMMIT:0:7} quay.io/azavea/spark:latest;
    docker push quay.io/azavea/spark:latest;
    fi
  - if [ -n "${TRAVIS_TAG}" ]; then
    docker tag quay.io/azavea/spark:${TRAVIS_COMMIT:0:7} quay.io/azavea/spark:${TRAVIS_TAG};
    docker push quay.io/azavea/spark:${TRAVIS_TAG};
    fi
