language: bash
services: docker

env:
  - VERSION=2.0 SPARK_VERSION=2.0.2 JRE_VERSION=8 HADOOP_VERSION=2.7
  - VERSION=2.1 SPARK_VERSION=2.1.0 JRE_VERSION=8 HADOOP_VERSION=2.7

script:
  - ./scripts/cibuild

deploy:
  - provider: script
    script: "scripts/cipublish"
    on:
      repo: azavea/docker-spark
      branch: master
